spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: "delivery"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: 8082
geo:
  host: localhost:5004